### ISSUE TITLE
Step does not finish

### ISSUE THREAD

**Issue by tobiasKaminsky** [ReactiveCircus/android-emulator-runner#104]
Thanks for your great effort to let us run emulator via GitHub Actions!

I have such a workflow:
```
test:
        runs-on: macOS-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Build gplay
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    ./gradlew assembleGplayDebug
            -   name: run tests
                uses: reactivecircus/android-emulator-runner@v2
                with:
                    api-level: 29
                    script:
                        ./gradlew gplayDebugExecuteScreenshotTests -Pandroid.testInstrumentationRunnerArguments.annotation=com.owncloud.android.utils.ScreenshotTest2
            -   name: upload failing results
                if: ${{ failure() }}
                run:
                    scripts/uploadReport.sh
```

I log I then  see:
```
You can review the execution report here: /Users/runner/work/android/android/build/reports/shot/verification/index.html

> Task :gplayDebugExecuteScreenshotTests FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gplayDebugExecuteScreenshotTests'.
> Screenshots comparision fail. Review the execution report to see what's broken your build.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 15s
68 actionable tasks: 33 executed, 35 up-to-date
Error: The process '/bin/sh' failed with exit code 1
/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
OK: killing emulator, bye bye
OK
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
eglMakeCurrent failed in binding subwindow!
```

So gradle step failed, sh exits with 1. 
Emulator gets killed, but then nothing happens.

Next step "upload failing results" is not executed, nor workflow finishes.

I then manually killed it.

**Comment by ychescale9** [comment]
Would you be able to share the full log?

**Comment by tobiasKaminsky** [comment]
Wow, thanks for fast reply :+1: 

https://github.com/nextcloud/android/runs/1379147005?check_suite_focus=true

As I am testing, you see that many commits ;-)

**Comment by tobiasKaminsky** [comment]
I moved the command in the same line with "script:" and now at least there are not those endless 
> eglMakeCurrent failed in binding subwindow!
but it does not help in terms of finishing the step.

https://github.com/nextcloud/android/pull/7009/checks?check_run_id=1379228010

**Comment by tobiasKaminsky** [comment]
gplayDebugExecuteScreenshotTests is from https://github.com/Karumi/Shot
If that helps…

**Comment by ychescale9** [comment]
I'm not familiar with the screenshot testing library but suspect it's to do with sdcard in API 30 system images (see [this issue](https://github.com/ReactiveCircus/android-emulator-runner/issues/56)).

I've done a bit of investigation [here](https://github.com/ReactiveCircus/android-emulator-runner/issues/102#issuecomment-719464713), but haven't figured out yet. Can you try with a lower API level (e.g. 29)?

**Comment by ychescale9** [comment]
Sorry you're already testing with API 29.

Can you try without `emulator-options`, with API 23 instead?

**Comment by tobiasKaminsky** [comment]
```
 -   name: run tests
                uses: reactivecircus/android-emulator-runner@v2
                with:
                    api-level: 29
                    script: ./gradlew gplayDebugExecuteScreenshotTests -Pandroid.testInstrumentationRunnerArguments.annotation=com.owncloud.android.utils.ScreenshotTest2
```
Thanks for your help!
Removing emulatorOption seems to help.

Now I need to find another way to have a specific resolution, as the pre-recorded screenshots are all in size 500x833.

**Comment by ychescale9** [comment]
You might already be doing this but if you can get it to work locally from the command line, it'll probably work with GitHub Action.

If you do specify `emulator-options`, you might want to keep `-no-window -gpu swiftshader_indirect`.

**Comment by tobiasKaminsky** [comment]
Thanks, indeed this was the problem: I somehow 🤷‍♂️ thought it would extend the options…

```
-   name: run tests
                uses: reactivecircus/android-emulator-runner@v2
                with:
                    api-level: 29
                    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
                    script: ./gradlew gplayDebugExecuteScreenshotTests -Pandroid.testInstrumentationRunnerArguments.annotation=com.owncloud.android.utils.ScreenshotTest2
            -   name: upload failing results
                if: ${{ failure() }}
                run:
                    scripts/uploadReport.sh
```

This now works!

Thanks!
