### ISSUE TITLE
Change in 2.14 breaks valid 2.13 configuration

### ISSUE THREAD

**Issue by edeckers** [ReactiveCircus/android-emulator-runner#113]
See also:
https://github.com/ReactiveCircus/android-emulator-runner/commit/02cf8052905776094f8ff998a2c717ef79445d24#r45455491

**Description**
The valid 2.13 configuration below hangs on version 2.14, because the script will infinitely wait for user input for:
`Do you wish to create a custom hardware profile? [no]`

_Valid 2.13 configuration_
```yaml
 - uses: reactivecircus/android-emulator-runner@v2
   with:
      api-level: 30
      script: ./gradlew connectedAndroidTest
      target: google_apis
      working-directory: './android'
```

**What I expect**
When I use the valid 2.13 configuration as presented above, the build will confirm the CLI question with "no" and continue.

**Steps to reproduce**
1. Build a configuration that does _not_ specify a `$profile`
2. Notice that the build will hang
