### ISSUE TITLE
Runner hangs installing build tools

### ISSUE THREAD

**Issue by sapuglha** [ReactiveCircus/android-emulator-runner#116]
Today I noticed that the runner hangs while trying to install latest build tools.

```
Run reactivecircus/android-emulator-runner@v2
  with:
    api-level: 29
    profile: pixel
    script: ./gradlew app:connectedDevDebugAndroidTest domain:connectedDebugAndroidTest
    target: default
    arch: x86
    avd-name: test
    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
    disable-animations: true
API level: 29
target: default
CPU architecture: x86
Hardware profile: pixel
SD card path or size: 
AVD name: test
emulator options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
disable animations: true
Script:
./gradlew app:connectedDevDebugAndroidTest domain:connectedDebugAndroidTest
Installing new cmdline-tools.
/usr/bin/unzip -q /Users/buildmachine/actions-runner/OrgWideRunner/_work/_temp/7caea691-806e-4246-be51-fb6e7a29e145
Installing latest build tools, platform tools, and platform.
/bin/sh -c \sdkmanager --install 'build-tools;30.0.3' platform-tools 'platforms;android-29' > /dev/null
```

Back from holidays so I'm not sure when it stopped working.

This is the job as I have in my workflow.
```
  instrumentation_test:
    needs: unit_test
    runs-on: [self-hosted, macos, android]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Instrumentation Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel
          script: ./gradlew app:connectedDevDebugAndroidTest

      - name: Archive Instrumentation Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: Instrumentation Test Results
          path: ./app/build/reports
```
