### ISSUE TITLE
Emulator never comes online

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveCircus/android-emulator-runner#118]
Hey! Apologies for the vague report, I don't really know where else to look. Here is our repro case: https://github.com/ZacSweers/ticktock/pull/46 (ci file is ci.yml). Let me know if I can help with any other details!

**Comment by ychescale9** [comment]
Looks like there's a conflict between your `android-sdk.sh` and the action's SDK installation:
```
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/Users/runner/Library/Android/sdk]!
```

The deprecated `$ANDROID_HOME` was recently removed from the path in favor of `$ANDROID_SDK_ROOT`.

Can you try pinging the version to `v2.13.0` or replacing `$ANDROID_HOME` in your workflow / script with `$ANDROID_SDK_ROOT`?

Removing `$ANDROID_HOME` seems like a bad call after all (here's another issue: https://github.com/ReactiveCircus/android-emulator-runner/issues/116). I'll revert it.

**Comment by ZacSweers** [comment]
Will give that a try!

**Comment by ZacSweers** [comment]
Looks like that worked

**Comment by Kiruel** [comment]
Hi, I got the same issue here. Trying to run on self hosted runner. And got:
```
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/Users/etiennetheodore/Library/Android/Sdk]!
emulator: Android emulator version 30.7.3.0 (build_id 7425822) (CL:N/A)
/Users/etiennetheodore/Library/Android/Sdk/platform-tools/adb shell getprop sys.boot_completed
adb: no devices/emulators found
The process '/Users/etiennetheodore/Library/Android/Sdk/platform-tools/adb' failed with exit code 1
```
And got a while infinite on this error:

```
adb: no devices/emulators found
The process '/Users/etiennetheodore/Library/Android/Sdk/platform-tools/adb' failed with exit code 1
/Users/etiennetheodore/Library/Android/Sdk/platform-tools/adb shell getprop sys.boot_completed
```

I have to try to replace my .env in my runner from ANDROID_HOME to ANDROID_SDK_ROOT. But got no change.

This is my setting for the action:
```
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.21.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
```
