### ISSUE TITLE
Emulator flakiness in Espresso tests

### ISSUE THREAD

**Issue by binglaianchor** [ReactiveCircus/android-emulator-runner#127]
Hello!

I've been getting failures around my espresso test runs where builds would pass only when we've re-triggered multiple times. ive tried to set a device but that also seems flaky. The tests always pass locally.

```
Run reactivecircus/android-emulator-runner@v2
  with:
    api-level: 25
    script: ./gradlew -PjacocoEnabled=true jacocoTestReport
    target: default
    arch: x86
    avd-name: test
    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
    disable-animations: true
  env:
    JAVA_HOME_8.0.282_x64: /Users/runner/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME: /Users/runner/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME_8_0_282_X64: /Users/runner/hostedtoolcache/jdk/8.0.282/x64
API level: 25
target: default
CPU architecture: x86
Hardware profile: 
SD card path or size: 
AVD name: test
emulator options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
disable animations: true
Script:
./gradlew -PjacocoEnabled=true jacocoTestReport

> Task :app:compileDebugUnitTestJavaWithJavac
> Task :app:packageDebug
> Task :app:testDebugUnitTest
> Task :app:jacocoTestReportDebug
> Task :app:kaptGenerateStubsReleaseKotlin
> Task :app:connectedDebugAndroidTest
Starting 23 tests on test(AVD) - 7.1.1

com.android.tests.authentication.login.LoginEspressoTest > loginInExistingUserWorksFromLoginScreen[test(AVD) - 7.1.1] FAILED 
	java.lang.AssertionError: expected:<5672> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
```

github workflow:
```
name: Unit/instrumented tests and generate test coverage

on:
  pull_request

jobs:
  testAndCoverage:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate jacoco coverage by running unit and instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 25
          script: ./gradlew -PjacocoEnabled=true jacocoTestReport
      - name: Upload test reports to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: app/build/reports/coverage/debug/report.xml
```
