### ISSUE TITLE
Android Emulator API 30 - Process System Isn't Responding dialog displayed, blocking any action

### ISSUE THREAD

**Issue by szymon-kazmierczak** [ReactiveCircus/android-emulator-runner#140]
Hello,

The Android emulator with API 30 is unusable as it launches with the "System Isn't Responding" dialog every time.

I need to use API 30 because of arm support - https://android-developers.googleblog.com/2020/03/run-arm-apps-on-android-emulator.html

Here's the relevant configuration bit:

```
 test:
    runs-on: macos-latest
    timeout-minutes: 40
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Launch Android Emulator
      uses: actions/android-emulator-runner@v2.15.0
      with:
        api-level: 30
        profile: Nexus 6
        target: google_apis_playstore
        arch: x86_64
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot-load -noaudio -no-boot-anim
        disable-animations: true
        script: |
```

I took a screenshot of the emulator running and this is what i get every single time.

![file2021-03-26-12-00-55](https://user-images.githubusercontent.com/30314949/112637795-6fccc100-8e36-11eb-9034-9cd273f84efd.png)
