### ISSUE TITLE
Instrumented Tests in Compose failing

### ISSUE THREAD

**Issue by igorescodro** [ReactiveCircus/android-emulator-runner#147]
Hello, everyone!

I'm facing some issues since I ported my application to Jetpack Compose.
Some of my tests are failing in the GitHub Action but are passing locally.
The error are very simple one, like `Reason: Expected exactly '1' node but could not find any node that satisfies`, meaning that the Composable node was not found. However it does not fail on emulator locally (tried on Nexus 5, Pixel 4 XL and Generic).

Currently my script is:

```
name: instrumented tests

on: [ push ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.15.0
        with:
          api-level: 29
          target: google_apis
          script: ./gradlew connectedCheck --stacktrace
```

Am I missing some configuration to work better with Jetpack Compose?

Thanks a lot for your help!
