### ISSUE TITLE
Unable to run Appium parallel tests

### ISSUE THREAD

**Issue by yavgel** [ReactiveCircus/android-emulator-runner#156]
Unable to run Appium parallel tests, because you are killing emus after the script has been done
 `OK: killing emulator, bye bye `

How can I set up 4 Android devices to run my Appium tests in parallel, please see my GH Actions yml below:

--------

```
name: Appium CI

on:
  repository_dispatch:
    types: [ kubernetes_deploy_mobile ]

jobs:
  build:
    runs-on: macos-latest # the machine type
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [ 29 ] #Google api level for example [25,23,28]
        target: [ default ]
    steps:
      - uses: actions/checkout@v2 #checkout the code
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install and Run Appium Server
        run: |
          chmod +x ./scripts/RunAppiumServer.sh # install and run appium server in the background
          ./scripts/RunAppiumServer.sh
      - name: EMU_1
        uses: ReactiveCircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          avd-name: 1st_Pixel_4_XL_API_30
          script: pwd
      - name: EMU_2
        uses: ReactiveCircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          avd-name: 2nd_Pixel_4_XL_API_30
          script: pwd
      - name: EMU_3
        uses: ReactiveCircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          avd-name: 3rd_Pixel_4_XL_API_30
          script: pwd
      - name: EMU_4
        uses: ReactiveCircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          avd-name: 4th_Pixel_4_XL_API_30
          script: pwd

      - name: Run Appium Tests
        run: ./gradlew cleanTestAndroidDemo testAndroidDemo --info
```
