### ISSUE TITLE
Option to increase logcat buffer size on boot

### ISSUE THREAD

**Issue by alexander-efremov** [ReactiveCircus/android-emulator-runner#169]
Hello there!
Is there an option to increase logcat buffer size on boot?

E.g.

```yml
- name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          log_buffer: 16M
          script: ./run.sh ${APP_NAME}`
```

and then getting:
```txt
emulator: Increasing screen off timeout, logcat buffer size to 16M.

emulator: Revoking microphone permissions for Google App.
```
