### ISSUE TITLE
Hangs for ever at stage "Installing system images"

### ISSUE THREAD

**Issue by SalomonBrys** [ReactiveCircus/android-emulator-runner#173]
Here is our configuration:

```yml
      - name: Check Android (macos)
        if: matrix.os == 'macos-latest'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          ndk: 21.3.6528147
          cmake: 3.10.2.4988404
          script: ./gradlew connectedCheck
```

The problem is that the sdkmanager hangs for ever at the stage:

```
Installing system images.
/bin/sh -c \sdkmanager --install 'system-images;android-29;default;x86_64' > /dev/null
```

I suppose we could get more info about why by removing the `> /dev/null`.
There should be an option to remove it (something like `showSdkManagerOutput` set to false by default).
