### ISSUE TITLE
Environment variables are unavailable in script

### ISSUE THREAD

**Issue by alexsegura** [ReactiveCircus/android-emulator-runner#19]
Hi,

When using environment variable in script, they seem to be escaped

The example below would just print `$GITHUB_WORKSPACE`

```yaml
steps:
  - ...
  - uses: reactivecircus/android-emulator-runner@v2
    with:
      ...
      script: |
        echo $GITHUB_WORKSPACE
```

The problem should be around there

https://github.com/ReactiveCircus/android-emulator-runner/blob/e756009f0de1bac9a9ce58d2ce1e8d5f5e72d1cb/src/main.ts#L79-L86
