### ISSUE TITLE
Screenshots have variable color tint

### ISSUE THREAD

**Issue by zommerfelds** [ReactiveCircus/android-emulator-runner#196]
Hi, not sure if this is related to this package or not but I couldn't find anything on the internet so far about this issue.

I'm running screenshot comparison tests on GitHub Actions, but the `screencap` output has a variable white tint depending on the run.

Do you have any ideas why this could be? Here are the screenshots captured by `adb exec-out screencap -p > blah.png`. I have a loop where I keep retrying until it matches.

![Android-SDK-built-for-x86_64-1440x2560](https://user-images.githubusercontent.com/1260622/138064105-821d3076-b788-427e-a292-3b202b90c2be.png)
![Android-SDK-built-for-x86_64-1440x2560-1634334088715640000](https://user-images.githubusercontent.com/1260622/138064150-b93d31dc-34f6-4a59-b4cb-c6e99cdb51a2.png)
![Android-SDK-built-for-x86_64-1440x2560-1634714960271083000](https://user-images.githubusercontent.com/1260622/138064171-5c222946-ce79-40c4-a4bc-e7681ac8f5b7.png)

Here's my setup:
```
      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ runner.os }}-v2
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          force-avd-creation: false
          arch: x86_64
          profile: Nexus 6
          target: google_apis
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          force-avd-creation: false
          arch: x86_64
          profile: Nexus 6
          target: google_apis
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: python test/test.py
```

Maybe this is a problem very specific to my game engine or game, but wanted to ask if anybody saw something similar.
