### ISSUE TITLE
Wrong screen resolution

### ISSUE THREAD

**Issue by the-coding-turtle** [ReactiveCircus/android-emulator-runner#200]
Hi,

I am creating screenshots with flutter drive, but no matter which device I choose, the height of the images is never correct.

For `Nexus 5X` the resolution is `1080 x 1794` and should be `1080 x 1920`.
For `Pixel` the resolution is `1080 x 1776` and should be `1080 x 1920`.
For `Pixel XL` the resolution is `1440 x 2392` and should be `1440 x 2560`.

Emulator:
```
- name: run emulator
   uses: reactivecircus/android-emulator-runner@v2
   with:
     api-level: 28
     profile: pixel
     force-avd-creation: false
     emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
     disable-animations: true
```

If I run flutter drive locally with the emulator the resolution for pixel 2 or nexus 5x is correct `1080 x 1920`.

I want to use the screenshots later in `fastlane frameit` and always receive the error `Unsupported screen size [1080, 1776] for path './screenshot.png'`

What am I doing wrong?

Thanks in advance!
