### ISSUE TITLE
Screen display size same for different profile

### ISSUE THREAD

**Issue by shaniperera** [ReactiveCircus/android-emulator-runner#201]
I have tried to run my UI tests in the CI environment using this Github action and specifying Nexus 6 as well as Pixel 3 XL/ Pixel Pro as the emulator hardware profile.
I am taking screenshots on failure to check for a constant failure, and found that the screen display size of the emulator is the same regardless of if I run the Github action with the profile of Nexus 6 or Pixel 3XL or Pixel Pro.
I would expect Nexus 6 to have a display size of 5.96" and Pixel 3XL to be 6.3".
```
# Execute tests
      - name: Run e2e tests
        id: run-e2e-tests
        timeout-minutes: 15
        uses: reactivecircus/android-emulator-runner@v2.21.0
        with:
          api-level: ${{ matrix.api-level }} #29
          profile: Pixel 3XL
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: <some script>
```
 For this reason, an element I want to click on is not in the view port (as expected in the test) and the test fails.
 
 Could you advise on this?
