### ISSUE TITLE
expose emulator's network

### ISSUE THREAD

**Issue by megetron** [ReactiveCircus/android-emulator-runner#211]
thanks for the great action.

is it possible to expose a network IP as well to this emulator?

```
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            adb -s emulator-5554 shell ip addr show wlan0
```
which shows the following result:
```
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 02:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
```

but when I try the same on my local machine  i get something with IP:
```
15: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:15:b2:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.16/24 brd 10.0.2.255 scope global wlan0
```

just wonder if this is something possible to do with the macos-latest runner?
