### ISSUE TITLE
Running with SD card makes the emulator not start

### ISSUE THREAD

**Issue by EmmanuelMess** [ReactiveCircus/android-emulator-runner#216]
See [here](https://github.com/TeamAmaze/AmazeFileManager/runs/5000208072?check_suite_focus=true) the working version, and [here](https://github.com/TeamAmaze/AmazeFileManager/runs/4999961694?check_suite_focus=true) the broken version.

This is the working script:
```yaml
  test_emulator:
    timeout-minutes: 30 # Emulator can get stuck
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        api-level: [21]#[16, 19, 28]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'gradle'
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          #sdcard-path-or-size: 50M
          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew :app:connectedCheck

```
