### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by sebastianbuechler** [ReactiveCircus/android-emulator-runner#261]
I followed this article in order to use your GitHub Action: https://www.etiennetheodore.com/integration-testing-with-ci/

When letting the action run, I get the following error: 
/Users/runner/hostedtoolcache/flutter/3.0.5-stable/x64/bin/internal/shared.sh: line 225: /Users/runner/hostedtoolcache/flutter/3.0.5-stable/x64/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable

The only thing I changed from the article was updating the flutter version to 3.0.5. So the yml file looks like this:
```
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
name: Flutter integration test
jobs:
  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [playstore]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      # Run integration test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/increment_success_test.dart

      # Update screenshot to artifact
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: screenshot
          path: ${{ matrix.path }}screenshots/
```

I read that this could be because of rosetta: https://github.com/flutter/flutter/issues/74511 But not sure how to integrate this into this workflow and if it is really intended to work like that.
