### ISSUE TITLE
Blank/Empty screenshot

### ISSUE THREAD

**Issue by cmonfortep** [ReactiveCircus/android-emulator-runner#273]
Hello, 

A part of another project, we were playing around if it's possible to take an screenshot when running some tests. We are having problems with that since all the screenshots we pull are empty/blank.

To reproduce it, it's as simple ase using the following steps in a github action.
```
      - name: Test
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          arch: x86_64
          target: google_apis
          profile: Nexus 6
          script: adb shell screencap -p /data/local/tmp/Screenshot.png; adb pull /data/local/tmp/Screenshot.png Screenshot.png;

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: device-screenshot
          path: ./*Screenshot.png
```

Are we missing something? is it expected that screenshots are blank/empty when using emulators inside github actions?

**Comment by mrk-han** [comment]
@cmonfortep By default the emulator is started headlessly with -no-window, this might be the reason screenshots are not showing up. Try explicitly overriding that in your emulator options and let me know how your screenshots are appearing after.

**Comment by cmonfortep** [comment]
Thanks, I've tested it multiple times with different setups and I'm always getting the same emtpy/blank png. 


This is the latest I tested, and no luck.
```
      - name: Android checks
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          arch: x86_64
          target: google_apis
          profile: Nexus 6
          emulator-options: -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: adb shell screencap -p /data/local/tmp/Screenshot.png; adb pull /data/local/tmp/Screenshot.png Screenshot.png;
```
