### ISSUE TITLE
Emulator doesn't start when caching is set up

### ISSUE THREAD

**Issue by repeato-qa** [ReactiveCircus/android-emulator-runner#278]
The emulator just never starts. This is the log we get:

```
Launch Emulator
  /bin/sh -c \printf 'hw.cpu.ncore=2
  ' >> /Users/runner/.android/avd/test.avd/config.ini
  /bin/sh -c \printf 'hw.ramSize=8096M
  ' >> /Users/runner/.android/avd/test.avd/config.ini
  Starting emulator.
  /bin/sh -c \/Users/runner/Library/Android/sdk/emulator/emulator -avd test -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &
  PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/Users/runner/Library/Android/sdk]!
  INFO    | Android emulator version 31.3.12.0 (build_id 9126400) (CL:N/A)
  emulator: INFO: path_getAvdSystemPath: AVD test has path /Users/runner/.android/avd/test.avd
  emulator: INFO: path_getAvdSystemPath: trying to check whether /Users/runner/Library/Android/sdk is a valid sdk root
  emulator: WARN: path_getAvdSystemPath: /Users/runner/Library/Android/sdk/system-images/android-29/default/x86/ is not a valid directory.
  emulator: WARN: path_getAvdSystemPath: emulator has searched the above paths but found no valid sdk root directory.
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  * daemon not running; starting now at tcp:5037
  * daemon started successfully
  adb: no devices/emulators found
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  adb: no devices/emulators found
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  adb: no devices/emulators found
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  adb: no devices/emulators found
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  adb: no devices/emulators found
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  adb: no devices/emulators found
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1

```
And this is the workflow file:
```
name: Run Repeato CLI

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  repeato-cli:
    name: Build and run repeato tests using REPEATO CLI
    runs-on: macos-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - uses: actions/checkout@v3

      - name: Checkout flutter app repo
        uses: actions/checkout@v3
        with:
          repository: repeato-qa/flutter-demo-app
          path: demo-app
          clean: false

      - name: Checkout workspace repo
        uses: actions/checkout@v3
        with:
          repository: repeato-qa/demo-workspace
          path: workspace-tests
          clean: false

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
          channel: 'stable'
      - run: cd demo-app && flutter pub get
      - run: cd demo-app && flutter build apk --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: demo-app/build/app/outputs/flutter-apk/app-x86_64-release.apk

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
    
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          target: google_apis
          profile: pixel_3a
          ram-size: 8096M
          script: echo "Generated AVD snapshot for caching."

      - name: Start Android emulator and run tests
        uses: ReactiveCircus/android-emulator-runner@v2.26.0
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          target: google_apis
          profile: pixel_3a
          ram-size: 8096M
          script: npx @repeato/cli-testrunner --workspaceDir "${GITHUB_WORKSPACE}/workspace-tests" --batchId 0 --licenseKey ${{ secrets.REPEATO_LICENSE_KEY }} --outputDir "${GITHUB_WORKSPACE}/batch-report"

```
