### ISSUE TITLE
Run script if test failed

### ISSUE THREAD

**Issue by yujincheng08** [ReactiveCircus/android-emulator-runner#284]
I would like to know if there can be a script that runs after the test fails. For example, my app may encounter a native crash during testing, and I can run a script to extract the tombstone from the AVD.

**Comment by mrk-han** [comment]
You can have an archive step which runs `if: failure()`, but that is outside of the scope of this action. 

```
       - uses: actions/upload-artifact@v3
         with:
          name: AVD tombstone 
          path: **/path/to/artifact/*.fileextension
```
