### ISSUE TITLE
Google Map doesn't work with Flutter

### ISSUE THREAD

**Issue by nicolas71640** [ReactiveCircus/android-emulator-runner#287]
Hello 

I've been using the android emulator action to run integration test for a flutter application using Google Maps plugin. 

However on the Android emulator, the GoogleMap Widget doesn't get "created", even if it works perfectly fine on my local machine with an emulator. 

I've reproduced the problem with a minimum of code. Here's the link of the https://github.com/nicolas71640/flutter_google_map_integration_test. 

You can check the Actions to see that Android Integration Tests job failed, and that the "onMapCreated" log doesn't appear. 

Here's the job :

```
android-integration_tests:
    name: Android Integration Tests
    runs-on: macos-latest
    env:
      GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      #Setup Flutter Environnement
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          api-level: 29
          profile: "pixel"
          script: flutter test integration_test --verbose 
```
        
And the test that fail: 
```
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  WidgetsFlutterBinding.ensureInitialized();

  GoogleMapsFlutterPlatform.instance.enableDebugInspection();

  testWidgets('testOnMapCreated', (WidgetTester tester) async {
    final Key key = GlobalKey();
    final Completer<bool> mapIdCompleter = Completer<bool>();

    print("pumpWidget");

    await tester.pumpWidget(Directionality(
      textDirection: TextDirection.ltr,
      child: GoogleMap(
        key: key,
        initialCameraPosition: _kInitialCameraPosition,
        mapToolbarEnabled: false,
        onMapCreated: (GoogleMapController controller) {
          print("onMapCreated");
          mapIdCompleter.complete(true);
        },
      ),
    ));

    print("Wait for onMapCreated");
    expect(await mapIdCompleter.future, true);
  });
}
```
