### ISSUE TITLE
Unable to start emulator, $ADB_VENDOR_KEYS not set

### ISSUE THREAD

**Issue by baconcheese113** [ReactiveCircus/android-emulator-runner#297]
In my `Create AVD and generate snapshot for testing` CI/CD step in github actions I get the following error

> This adb server's $ADB_VENDOR_KEYS is not set

It seems like the device is able to boot correctly, but not sure what happens afterwards

https://github.com/baconcheese113/handle-it-app/actions/runs/3643230559/jobs/6151237985

```shell
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  adb: device offline
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  adb: device offline
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  adb: device offline
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  adb: device offline
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  INFO    | boot completed
  INFO    | boot time 67322 ms
  INFO    | Increasing screen off timeout, logcat buffer size to 2M.
  INFO    | Revoking microphone permissions for Google App.
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  adb: device unauthorized.
  This adb server's $ADB_VENDOR_KEYS is not set
  Try 'adb kill-server' if that seems wrong.
  Otherwise check for a confirmation dialog on your device.
  /Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
  adb: device unauthorized.
  This adb server's $ADB_VENDOR_KEYS is not set
  Try 'adb kill-server' if that seems wrong.
  Otherwise check for a confirmation dialog on your device.
```

**Comment by baconcheese113** [comment]
Able to get it to work by disabling caching
```yml
      # - name: Gradle cache
      #   uses: gradle/gradle-build-action@v2.3.3
      
      # - name: AVD cache
      #   uses: actions/cache@v3.0.11
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd/*
      #       ~/.android/avb*
      #     key: avd-${{ matrix.api-level }}

      # - name: Create AVD and generate snapshot for caching
      #   if: steps.avd-cache.outputs.cache-hit != true
      #   uses: reactivecircus/android-emulator-runner@v2.27.0
      #   with:
      #     api-level: ${{ matrix.api-level }}
      #     profile: Nexus 5
      #     target: playstore
      #     arch: x86_64
      #     force-avd-creation: false
      #     emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     disable-animations: false
      #     script: echo "Generated AVD snapshot for caching."

      - name: Run integration tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          profile: Nexus 5
          target: playstore
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: cd handle-it-app && flutter test integration_test --flavor devtest --verbose

```

Is there a way to use caching with the emulator?
