### ISSUE TITLE
Question: reliable setup for using with BuildJet

### ISSUE THREAD

**Issue by IvanHorchakov** [ReactiveCircus/android-emulator-runner#306]
Hi, there! I'm running Flutter integration tests using the "buildjet-4vcpu-ubuntu-2204" runners (4 vCPU | 16 GB) with GitHub Action's "matrix" to achieve parallelization. 
Here is my setup (Flutter 3.3.10, Java SDK 11):
```
uses: reactivecircus/android-emulator-runner@v2
with:
  api-level: 30                  
  target: google_atd             
  arch: x86                      
  channel: canary                
  profile: pixel_5               
  script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/suites/${{ matrix.test-set }}_smoke_suite.dart --enable-software-rendering
```
But it seems that mentioned setup isn't the better one - cuz tests can be green locally (on Pixel 5 emulator) but will be red in CI, and each new run on CI will paint different tests in red - from my point of view it can be some kinda performance problems. Are those ATDs not reliable ones for complex Flutter integration (UI) tests? 
Please, provide advice for a reliable setup for using with BuildJet with API 30-31.
TY in advance!
