### ISSUE TITLE
"Cache not found for input keys: avd-29"

### ISSUE THREAD

**Issue by kirillzh** [ReactiveCircus/android-emulator-runner#310]
AVD caching does not seem to work, getting `Cache not found for input keys: avd-29` log and seeing AVD being recreated on each run. Workflow setup:

```
- name: AVD cache
  uses: actions/cache@v3
  id: avd-cache
  with:
    path: |
      ~/.android/avd/*
      ~/.android/adb*
    key: avd-29

- name: create AVD and generate snapshot for caching
  if: steps.avd-cache.outputs.cache-hit != 'true'
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: 29
    force-avd-creation: false
    emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
    disable-animations: false
    script: echo "Generated AVD snapshot for caching."

- name: instrumented tests
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: 29
    working-directory: ./app
    force-avd-creation: false
    emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
    disable-animations: true
    target: google_apis
    script: bin/gradle connectedCheck
```
