### ISSUE TITLE
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/home/runner/.android/sdk]!

### ISSUE THREAD

**Issue by shubhampatel-hotstar** [ReactiveCircus/android-emulator-runner#333]
Requirement: 
- We want to execute Android ui-tests using android-emulator-runner, which we want to be hosted upon our own Linux VMs.

Issue:
- I am getting presently the issue as stated above for which the job completes w/o launching an emulator for which tests aren't performed (screenshots attached below herein).
<img width="1383" alt="Screenshot 2023-03-27 at 7 41 07 PM" src="https://user-images.githubusercontent.com/88380230/227965159-40853b75-31fd-43a9-bff1-b258ca8f044d.png">
<img width="1385" alt="Screenshot 2023-03-27 at 7 40 48 PM" src="https://user-images.githubusercontent.com/88380230/227965263-e29e6f94-e575-4e14-aa84-6abfa0edb231.png">

Code snippet:
```
  ui-tests:
    name: ui-tests
    runs-on: [ our-custom-runner ] // Hosted on a Linux VM
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ google_apis ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{inputs.JAVA_VERSION}}

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Execute tests on marketplace emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86
          profile: Nexus 6
          force-avd-creation: false
          emulator-build: 7425822
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./execute_ui_tests.sh

      - name: Upload coverage reports
```
