### ISSUE TITLE
How to choose emulator device?

### ISSUE THREAD

**Issue by chris-rutkowski** [ReactiveCircus/android-emulator-runner#34]
Hello,
I can't find it in the readme, perhaps `emulator-build`.
I would like to specify the device, for example, Pixel 2 or Nexus 6P.

The problem is that on the emulator that is created (without specifying any configuration apart from API level 29) some elements are unexpectedly off-screen and we would need to scroll to them first, before click action.

Kind regards
Chris

**Comment by ychescale9** [comment]
That's `profile`.

```
with:
    api-level: 29
    target: google_apis
    arch: x86_64
    profile: Nexus 6
    script: ./gradlew connectedCheck
```
To get a list of all profiles available, run `$ANDROID_HOME/tools/bin/avdmanager list` and refer to the results under "Available Android Virtual Devices".
