### ISSUE TITLE
Job hangs after unknown crash

### ISSUE THREAD

**Issue by safa007** [ReactiveCircus/android-emulator-runner#342]
We recently started experiencing this issue where we see a crash at the end of the Terminate emulator step, and after this step the job just hangs infinitely until it's cancelled or times out. The logs aren't really helpful, we just see a `UniversalExceptionRaise: (os/kern) failure (5)` at the very end of the job. It does seem like the AVD creation is successful however.

I tried resetting the machine this is happening on, and after 2 successful runs we started seeing the issue again. I've tested on v2.25.0 and v2.28.0 and the result is the same on both versions.

Has anyone experienced this recently?

EDIT: After setting `force-avd-creation` to `false` we are still getting the `UniversalExceptionRaise: (os/kern) failure (5)` error however the job does not hang and it correctly moves on to the next step. So it seems this is only happening when a new AVD is being created. We set `force-avd-creation` to `true` on every test run in order to prevent out of memory issues on the emulator.

EDIT2: Still seeing the issue with `force-avd-creation` to `false` as well.

```
Generated AVD snapshot
::group::Terminate Emulator
Terminate Emulator
  /Users/administrator/.android/sdk/platform-tools/adb -s emulator-5554 emu kill
  saving arm snapshot.... !!!
  
  OK: killing emulator, bye bye
  OK
  INFO    | Wait for emulator (pid 10852) 20 seconds to shutdown gracefully before kill;you can set environment variable ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL(in seconds) to change the default value (20 seconds)
  ::endgroup::
saving done.... !!!

[10854:273912:20230616,105830.126506:WARNING crash_report_exception_handler.cc:235] UniversalExceptionRaise: (os/kern) failure (5)
```

Here's our GHA setup
```
      - name: Create AVD
        uses: reactivecircus/android-emulator-runner@v2.25.0
        with:
          api-level: 29
          arch: arm64-v8a
          profile: pixel_5
          avd-name: macOS-avd-arm64-v8a-29
          disk-size: 16G
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          channel: canary
          disable-animations: false
          script: echo "Generated AVD snapshot"
```

**Comment by safa007** [comment]
Solved.

For those of you that are struggling with this as well the issue turned out to be the emulator version. One of the latest releases 32.1.12 has a [known issue](https://issuetracker.google.com/issues/275278635) which has been fixed in the [latest emulator release](https://developer.android.com/studio/releases/emulator#32-1-13). Make sure you are adding `target: google_apis` to receive the latest emulator version.

**Comment by carlospontual** [comment]
@safa007 how did you fix it? I've changed my target to `google_apis` but I'm still getting my jobs hanging without being able to kill the emulator...

here's my config:
```
      with:
        api-level: 30
        arch: arm64-v8a
        channel: stable
        target: google_apis
        profile: pixel_6
        avd-name: Test_Pixel6_Google_fhd_2
        force-avd-creation: false
        emulator-options: -no-window -gpu host -noaudio -no-boot-anim -camera-back none
        disable-animations: true
```

PS: if the AVD is re-created, I get the same exception you listed above (`UniversalExceptionRaise: (os/kern) failure (5)`) but the job doesn't hang...

Thanks!
