### ISSUE TITLE
I'm getting The process '/bin/sh' failed with exit code 1 when just trying to start the emulator

### ISSUE THREAD

**Issue by tking16** [ReactiveCircus/android-emulator-runner#349]
Hi, just started using this plugin as I had some issues booting up an emulator from actions myself. It doesn't seem to working for me though. It's probably something simple I'm missing

- I'm using an M2 Mac Mini
- [Full run logs](https://gist.github.com/tking16/047d38479073b6d9b55dc6dcd6cb176f)

Step is as follows:
```
    steps:
      - name: Create first emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          ram-size: 4000
          profile: Nexus 9
          arch: arm64-v8a
          script: echo creation finished
```
