### ISSUE TITLE
`PANIC: Avd's CPU Architecture 'arm64' is not supported by the QEMU2 emulator on x86_64 host.`

### ISSUE THREAD

**Issue by torokati44** [ReactiveCircus/android-emulator-runner#386]
I'm trying to set up testing for Ruffle on Android here: https://github.com/ruffle-rs/ruffle-android/pull/104/files

But am running into the https://github.com/ruffle-rs/ruffle-android/actions/runs/8449274575/job/23143034711?pr=104#step:7:69

I've tried several different sets of options (see Actions history), but all seemed to give the same error.

How come QEMU2 can't emulate ARM64? Do I need to run it on `macos-latest` for the M1 chip?

It's important that the arch is `arm64-v8a` due to issues like: https://github.com/ruffle-rs/ruffle-android/issues/63

**Comment by torokati44** [comment]
(Gave up on this for now, for a different reason, so closing, sorry for the spam.)

**Comment by ronenfe** [comment]
How are we supposed to run Android Auto emulator on intel processor?

**Comment by merlinpaypal** [comment]
@ychescale9 I'm getting this exact issue. What can I do to fix this?

https://github.com/paypal/paypal-messages-android/actions/runs/9064074649/job/24902595569#step:4:75

```
  test_instrumentation:
    name: Instrumentation Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Instrumentation Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck --info | tee connectedCheck.log
```
