### ISSUE TITLE
Running shell script 

### ISSUE THREAD

**Issue by GauravP123** [ReactiveCircus/android-emulator-runner#40]
can I run shell script once emulator boots up? 
Workflow looks like

        - name: Instrumentation tests
          uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 29
            arch: x86
      - name: script tests
        run: ./test.sh`
i am doing some custom logic inside test.sh
with this, its give ` Input required and not supplied: script`

**Comment by ychescale9** [comment]
Yes you can run a script! In fact you have to provide a script to be run once the emulator is booted, as indicated by the error you got.

Something like this should work:
```
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./test.sh
```
