### ISSUE TITLE
 adb: device 'emulator-5554' not found

### ISSUE THREAD

**Issue by alirezaeiii** [ReactiveCircus/android-emulator-runner#404]
Here is my scrip to start the emulator : 

```
name: Android Instrumentation Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android_test:
     name: Running Android Tests
     runs-on: macos-13
     continue-on-error: true
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
           api-level: 33
           target: default
           arch: x86_64
           profile: Nexus 4
           emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load
           script: |
            adb wait-for-device
            adb shell input keyevent 82
           ./gradlew connectedAndroidTest --continue

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: '**/build/reports/androidTests/connected/'
```

It seems device is booted successfully.
When it want to run test, it prints :

```
Execution failed for task ':features:feature-setting:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!
```
 I am runnung on macOS 13, so why this happens? Is it something wrong in my script for Github Action?

Here is the sample : https://github.com/alirezaeiii/TMDb-Compose-Playground
