### ISSUE TITLE
The pipeline fails with "Emulator is out of date" error

### ISSUE THREAD

**Issue by kotvertolet** [ReactiveCircus/android-emulator-runner#41]
Hi! I have the following android.yml:
```
name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [19, 25, 29]
        target: [default]
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedCheck
```

It is almost a copy past of the config provided in **Usage** section of your **readme.md**. When I trying to run this config it fails every time with the following error:

```
emulator: Cold boot: requested by the user
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```

Any suggestions?
