### ISSUE TITLE
Update default value of working-directory when is defined in default section

### ISSUE THREAD

**Issue by eduardoleolim** [ReactiveCircus/android-emulator-runner#422]
If I have a job with a custom working directory, I must to define the working directory in the emulator step again

```yaml
jobs:
  name: 🧪 Android Testing
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./app # Working directory for all steps 
  steps:
    
    ...

     - name: 🧪 Test
       uses: reactivecircus/android-emulator-runner@v2
       with:
         api-level: 35
         arch: x86_64
         target: google_apis
         emulator-port: 5554
         script: ./gradlew connectedAndroidTest
         working-directory: ./app # I have to set working directory again

```
f
