### ISSUE TITLE
API-LEVEL does not work with latest version within the latest sdk like (35-ext15)

### ISSUE THREAD

**Issue by TimoPtr** [ReactiveCircus/android-emulator-runner#429]
Google started to release images like `system-images;android-35-ext15;android-wear;arm64-v8a`. Right now in the current version of this Action we can't use it.

We should either add a `suffix` option to keep api-level a number or parse the number in api-level.

Something like
```
 - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: "35-ext15"
```
OR
```
 - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: "35"
          api-level-sufix: "-ext15"
```
