### ISSUE TITLE
TimeoutException after 12 minutes

### ISSUE THREAD

**Issue by Josehdez96** [ReactiveCircus/android-emulator-runner#441]
Hello! I'm trying to run an integration test that doesn't contain anything in it just to make sure that the emulator runs first. However running below .yml file, I'm getting this error. **Do you understand what may be happening there? Why is throwing that TimeoutException in a test that does not contain anything**.

```
Checking the license for package CMake 3.22.1 in /usr/local/lib/android/sdk/licenses
License for package CMake 3.22.1 accepted.
Preparing "Install CMake 3.22.1 v.3.22.1".
"Install CMake 3.22.1 v.3.22.1" ready.
Installing CMake 3.22.1 in /usr/local/lib/android/sdk/cmake/3.22.1
"Install CMake 3.22.1 v.3.22.1" complete.
"Install CMake 3.22.1 v.3.22.1" finished.
❌ loading /home/runner/work/kiosk_fdotf/kiosk_fdotf/integration_test/features/check_in/check_in_test.dart (failed)
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1517:47                      _rootRun
  dart:async/zone.dart 1422:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1525:13                      _rootRun
  dart:async/zone.dart 1422:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart [410](https://github.com/mgmri-dge/kiosk_fdotf/actions/runs/15913130270/job/44885081956#step:11:414):19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 441:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 194:12      _RawReceivePort._handleMessage

Error: 0 tests passed, 1 failed.
adb uninstall failed: ProcessException: Process exited abnormally with exit code 1:
Failure [DELETE_FAILED_INTERNAL_ERROR]
  Command: /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 uninstall com.mgmresorts.kiosk.fdotf
Error: The process '/usr/bin/sh' failed with exit code 1
Terminate Emulator
  /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 emu kill
  OK: killing emulator, bye bye
  OK
INFO         | Wait for emulator (pid 3479) 20 seconds to shutdown gracefully before kill;you can set environment variable ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL(in seconds) to change the default value (20 seconds)
```

.yml file.
```yaml
name: Run Integration Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  run_integration_tests:
    name: "Run Integration Tests"
    if: contains(github.event.pull_request.labels.*.name, 'Run Integration Tests')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4

    - name: Install flutter
    /* Install Flutter SDK */

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'adopt'

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Install Dependencies
      run: |
        flutter pub get
  
    - name: Run Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: default
        arch: x86_64
        profile: pixel_2
        avd-name: "MicroTouch-All-In-One"
        cores: 4
        ram-size: 2048M
        disk-size: 4096M
        emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load
        script: |
            echo "Run tests"
            flutter test integration_test --flavor qa4
```
