### ISSUE TITLE
Camera settings are not passed to emulator

### ISSUE THREAD

**Issue by unickq** [ReactiveCircus/android-emulator-runner#443]
```bash
emulator -port 5554 -avd test -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -no-metrics -camera-front emulated -camera-back virtualscene
```
creates `/home/runner/.android/avd/test.avd/config.ini`
with 

```config
hw.camera.back = emulated
hw.camera.front = none
```

```yml
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ env.android_target }}
          api-level: ${{ env.android_api_level }}
          arch: ${{ env.android_arch }}
          profile: ${{ env.android_profile }}
          force-avd-creation: true
          cores: ${{ env.android_cpu }}
          ram-size: ${{ env.android_ram }}
          heap-size: ${{ env.android_heap }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -no-metrics -camera-front emulated -camera-back virtualscene
         
```

Was anyone able to fix that?

Adding this into script section doesn't help because emulator is already booted
```
            echo "hw.camera.front=emulated" >> ~/.android/avd/test.avd/config.ini
            echo "hw.camera.back=virtualscene" >> ~/.android/avd/test.avd/config.ini
```
