### ISSUE TITLE
Starting up the emulator takes too long (even on macOs VMs)

### ISSUE THREAD

**Issue by sergialonsaco** [ReactiveCircus/android-emulator-runner#47]
I've implemented an action for my repo using your emulator android to run a Flutter drive test.
When executing the step were the emulator needs to start and run the tests, it takes too long, over 15minutes. 

Is there a way to make them run faster?

Here the action I'm using:
```
name: flutter drive

on:
  push:
    branches: 
      - develop

jobs:
  drive_android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Flutter pub get
        run: |
          flutter precache
          flutter doctor -v
          flutter pub get
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2.6.1
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --target=test_driver/app.dart
```

Thanks you so much!
