### ISSUE TITLE
Doesn't support the latest NDK 21.0.6113669

### ISSUE THREAD

**Issue by yongce** [ReactiveCircus/android-emulator-runner#48]
A problem occurred configuring project ':jniLib'.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 18.1.5063045, 18.1.5063045

Maybe the CMake version needs to be updated. See https://github.com/actions/virtual-environments/issues/517 .

**Comment by ychescale9** [comment]
Hi. NDK support has not been tested yet. I’ll look into it next week.

**Comment by andreynovikov** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669

It worked on November 2019

**Comment by ychescale9** [comment]
Can you try to pin the action to this version as see if it works?

`uses: reactivecircus/android-emulator-runner@v2.4.0`

**Comment by andreynovikov** [comment]
This helped: https://github.com/actions/virtual-environments/issues/578#issuecomment-605886387

**Comment by yongce** [comment]
@ychescale9 It seems that v2.4.0 didn't fix the issue.

Run reactivecircus/android-emulator-runner@v2.4.0
API level: 21
target: default
CPU architecture: x86_64
Hardware profile: Nexus 6
emulator options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
disable animations: true
Script:
./gradlew connectedCheck
...
> Configure project :jniLib
WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':jniLib'.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 18.1.5063045, 18.1.5063045


See the logs at https://github.com/yongce/AndroidLib/runs/573490177?check_suite_focus=true

**Comment by ychescale9** [comment]
I'm starting to work on this. Right now I'm thinking that we ask user to specify **both** the `ndk` and `cmake` versions if they need NDK support:

```
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        ndk: 21.0.6113669
        cmake: 3.10.2.4988404
        script: ./gradlew connectedCheck
```

@yongce does this make sense? are there cases when you need multiple versions of `cmake` / `ndk` installed?
