### ISSUE TITLE
"Google Play Services not supported" error even when targetting google_apis

### ISSUE THREAD

**Issue by another-dave** [ReactiveCircus/android-emulator-runner#5]
I'm seeing an error when running my tests of:

> [App name] won't run without Google Play services, which are not supported by your device.

Even when targetting `google_apis`. Here's the YAML snippet:

```
jobs:
  test:
    runs-on: macOS-latest
      strategy:
        matrix:
          api-level: [29]
          target: [google_apis]
          arch: [x86]
```

I've added screenshots in too and can see that the Activities are getting displayed OK, but with the Google Play Service modal dialog in front which is causing the tests to fail.

I can't see any warnings or errors in my build log with `--info` or `--stacktrace` enabled, and tests are just failing with a `NoMatchingViewException` because of the dialog.

Any ideas what may be causing this?  I'm using Android 10 / API level 29 on a local emulator and tests pass with no issues.

Let me know if you need more details.
