### ISSUE TITLE
Instrumentation run failed but works well locally

### ISSUE THREAD

**Issue by lopspower** [ReactiveCircus/android-emulator-runner#53]
Hello,

First of all, thank you for your work.

I have a clean architecture project with 3 modules (data, domain and presentation). I have instrumentals tests on both presentation and data. These tests work perfectly well locally but not with your solution. Indeed, only the data module tests work but not the presentation ones.

I tried to display more info with `--info` or `--debug` but I don't have more information.
Here is the error message:

```
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
```

Here is my configuration:

```
  emulator:
    name: Run Android Tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 23, 29]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run All Android Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew :presentation:connectedDebugTestAndroidTest --info
```
Do you have any information about what wrong here ?
