### ISSUE TITLE
Need an option to configure the build failure behavior

### ISSUE THREAD

**Issue by yongce** [ReactiveCircus/android-emulator-runner#54]
I configured the "strategy/matrix" as following:

```
    strategy:
      matrix:
        api-level: [21, 23, 29]
        target: [default, google_apis]
```

It's expected to start 6 builds. But if one of them is failed, the other builds will be canceled. This behavior should be configurable. In my case, I want the other builds to continue.
