### ISSUE TITLE
Is there option to enable sdcard?

### ISSUE THREAD

**Issue by uziasferreirazup** [ReactiveCircus/android-emulator-runner#56]
I get this error when run my test, I execute screen shot tests and get this error:
 Is your sdcard directory read-only?

**Comment by ychescale9** [comment]
I haven't tested the action with sdcard / external storage. Would you be able to share the full error log, your CI workflow, your test that causes this issue (e.g. are you writing to external storage)?

We may need some additional action inputs for configuring sdcard as this can't be done in the custom `script` after the emulator is already running.

**Comment by uziasferreirazup** [comment]
[logs_86.zip](https://github.com/ReactiveCircus/android-emulator-runner/files/4503326/logs_86.zip)
I used this library from facebook to execute tests: https://github.com/facebook/screenshot-tests-for-android

**Comment by ychescale9** [comment]
Thanks. Does [this](https://github.com/facebook/screenshot-tests-for-android/issues/162#issuecomment-385088965) help?

**Comment by uziasferreirazup** [comment]
Not, because I need execute these lines after create emulator and in your steps, you create emulator and run a script and kill after

**Comment by ychescale9** [comment]
Please see my comment [here](https://github.com/ReactiveCircus/android-emulator-runner/issues/57#issuecomment-616842298).

So it works if you put everything in the `script` block?

**Comment by uziasferreirazup** [comment]
Sorry about delay to answer you, I change my strategy, I created another emulator with API level 25(this resolve the error about sdcard),  but now I got another error about the screenshots there are not equal, like I set the profile "Nexus 5" but I don't what density the device was created, I think the machine create a device with different density

**Comment by uziasferreirazup** [comment]
[logs_133.zip](https://github.com/ReactiveCircus/android-emulator-runner/files/4513710/logs_133.zip)
I sent my long, but I try many things like  I remove this line:              `emulator-options: "-no-window -skin 1080x1920"` in another workflow to test and continues the error

**Comment by ychescale9** [comment]
Can you share your full workflow?

**Comment by uziasferreirazup** [comment]
```
name: Beagle Android Pull Request

on:
    pull_request:
        branches: [master]
        paths:
            - 'android/**'
jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - uses: malinskiy/action-android/install-sdk@release/0.0.5
            - name: run screen shot tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 25
                arch: x86_64
                target: google_apis
                profile: Nexus 5
                emulator-options: "-no-window -skin 1080x1920"
                script: ./gradlew executeScreenshotTests
            - name: Install Fastlane
              run: bundle install
            - name: Run pr check
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: bundle exec fastlane android pull_request_verification
```
