### ISSUE TITLE
Emulator get killed after running script

### ISSUE THREAD

**Issue by natintosh** [ReactiveCircus/android-emulator-runner#57]
Hi @ychescale9, I actually don't know what's run but any time I use your action it kills the emulator after booting

```
    - name: Setup android emulator of drive test
      uses: ReactiveCircus/android-emulator-runner@v2.7.0
      with:
        api-level: 29
        script: flutter devices
```

```
Emulator booted.
adb shell input keyevent 82
Disabling animations.
adb shell settings put global window_animation_scale 0.0
adb shell settings put global transition_animation_scale 0.0
adb shell settings put global animator_duration_scale 0.0
sh -c \flutter devices
emulator: INFO: boot completed
emulator: INFO: boot time 52579 ms
emulator: Increasing screen off timeout, logcat buffer size to 2M.
emulator: Revoking microphone permissions for Google App.
1 connected device:

Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
adb -s emulator-5554 emu kill
OK: killing emulator, bye bye
OK
emulator: Discarding the changed state: command-line flag
emulator: WARNING: Discarding the changed state (command-line flag).
```

**Comment by ychescale9** [comment]
Hi, the log looks fine as `fluter devices` just shows the currently connected devices right?

The emulator is always killed after everything in the `script` has been executed (success or failed), otherwise the action will never complete.

Are you having trouble running other commands in `script`?

**Comment by natintosh** [comment]
Thanks for your quick response @ychescale9 

build I still get this error before my later on

```
  flutter drive --target=./example/test_driver/app/app.dart
  shell: /bin/bash -e {0}
No devices found.
##[error]Process completed with exit code 1.
```

```
jobs:
  test:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Flutter CI
      uses: takuyaohashi/setup-flutter@v1 
    - run: flutter doctor
    
    - name: Setup android emulator of drive test
      uses: ReactiveCircus/android-emulator-runner@v2.7.0
      with:
        api-level: 29
        script: flutter devices
        
    - run: flutter pub get
      
    - name: Run dropdown drive test
      run: flutter drive --target=./example/test_driver/app/app.dart
```

**Comment by ychescale9** [comment]
So the emulator is only available in that 1 step, once `Setup android emulator of drive test` is finished, the emulator process killed. In fact any background processes won't run across multiple steps.

Try something like this instead:

```
jobs:
  test:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Flutter CI
      uses: takuyaohashi/setup-flutter@v1 
    - run: flutter doctor
    
    - name: Setup android emulator and run tests
      uses: ReactiveCircus/android-emulator-runner@v2.7.0
      with:
        api-level: 29
        script: |
          flutter devices
          flutter pub get
          flutter drive --target=./example/test_driver/app/app.dart
```
