### ISSUE TITLE
ConnectedCheck tests are failing (IOException)

### ISSUE THREAD

**Issue by dennisguse** [ReactiveCircus/android-emulator-runner#58]
We are using for OpenTracks [1] the android-emulator-runner and so far it was working very nicely!
However, recently we implemented tests doing file system operations and these are failing on Github Actions while working locally.

# Details
We have PR (https://github.com/OpenTracksApp/OpenTracks/pull/194#partial-pull-merging) that adds test for file system operations that were not checked before.
Sadly this results in 
https://github.com/OpenTracksApp/OpenTracks/pull/194/checks?check_run_id=617933592
```
de.dennisguse.opentracks.content.provider.CustomContentProviderUtilsTest > testDeleteWaypoint_onlyOneWayPointWithPhotoUrl[test(AVD) - 5.0.2] FAILED 
	java.lang.RuntimeException: java.io.IOException: open failed: ENOENT (No such file or directory)
	at de.dennisguse.opentracks.content.data.TestDataUtil.createWaypointWithPhoto(TestDataUtil.java:99)
```

Are there some limitations within the Android Emulator that prevents us from doing read/writing files?

# Github Actions configuration
```
#https://github.com/marketplace/actions/android-emulator-runner
name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: ./gradlew connectedCheck
```

[1] https://github.com/OpenTracksApp/OpenTracks/
