### ISSUE TITLE
AVD launch options

### ISSUE THREAD

**Issue by natario1** [ReactiveCircus/android-emulator-runner#6]
Hi @ychescale9 , thanks for your work! I'd love to have more control over the emulator launch options. Any chance of making them configurable?

```yaml
        with:
          api-level: ...
          emulator-options: -no-snapshot -camera-back emulated
          script: ...
```

If not specified, it could default to what you currently have:  -no-snapshot -noaudio -no-boot-anim . I can probably set up a PR if you want.
