### ISSUE TITLE
allow multiple targets

### ISSUE THREAD

**Issue by yigit** [ReactiveCircus/android-emulator-runner#72]
It would be really nice if I could set multiple targets in 1 action.
It is possible to do w/ matrix build but when the build itself is large, running it in parallel is not great. (lots of repeated builds)

I've tried executing multiple actions but second one fails when it tries to download the command line tools:

https://github.com/ReactiveCircus/android-emulator-runner/blob/master/src/sdk-installer.ts#L16

(mkdir fails since it already exists). 

I'm looking for something like this:

```
- name: Run Integration Tests
      uses: ReactiveCircus/android-emulator-runner@v2.8.0
      with:
        api-levels: [21, 24, 26, 29] 
        arch: x86_64
        script: ./gradlew connectedCheck --stacktrace
```

It could be even better if it invoked all emulators at once but that might overload the CI so it is fine if each one runs 1 by 1. The whole goal here is to avoid the preliminary build steps.

A possible workaround is to build the apk in 1 job and depend on its apk output in another job and run it via adb but that is also quite custom and invoking the test via gradle is still preferable.

**Comment by ychescale9** [comment]
> I've tried executing multiple actions but second one fails when it tries to download the command line tools:

Could you share snippet of your workflow with which you run into this issue? AFAIK the `cmdline-tools` directory doesn't exist on the VMs yet. Or have you created that directory manually in an earlier step?

As for running tests on multiple emulator instances in a single job, is the goal to save the time spent on assembling the apk and test apk? With build matrix and parallel jobs, though the `assembleXxx` tasks etc are repeated in multiple jobs, they all run in parallel. So I'm not able to see the benefits of running the assemble tasks once in 1 job.

I also doubt we'll have much success running multiple instances of emulators in the background. If we had to launch 1 emulator -> run the script -> kill emulator -> start next emulator -> run script again -> kill emulator .... it has to be order of magnitude slower than using build matrix.

Maybe I'm missing some context here, so if you're able to share your high-level workflow setup / goals that'd be great!

**Comment by ychescale9** [comment]
Oh I think I know what your tried to do now:

```
- name: run tests on API 21
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 21
- name: run tests on API 24
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
- name: run tests on API 26
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 26
- name: run tests on API 29
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
```

Yeah I haven't tested this scenario at all (and I'll fix that `mkdir` issue).

With this setup the `assembleXxx` tasks in subsequent jobs would be `UP-TO-DATE`, but do you have something that forces you to run these in a single build such that you don't care if they are not as fast as they can be?
