### ISSUE TITLE
Support multiple actions sequentially in a single job

### ISSUE THREAD

**Issue by ychescale9** [ReactiveCircus/android-emulator-runner#73]
In some cases users might do the following:

```
- name: test on API 21
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: 21
    script: ./gradlew connectedCheck
- name: test on API 24
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: 24
    script: ./gradlew connectedCheck
- name: test on API 26
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: 26
    script: ./gradlew connectedCheck
- name: test on API 30
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: 30
    script: ./gradlew connectedCheck
```

This current fails starting from the second job due to some of the operations not being idempotent.
