### ISSUE TITLE
It still can't connect to device

### ISSUE THREAD

**Issue by nzackoya** [ReactiveCircus/android-emulator-runner#85]
Loading local repository...                                                     
41
[=========                              ] 25% Loading local repository...       
42
[=========                              ] 25% Fetch remote repository...        
43
[=======================================] 100% Fetch remote repository...       
44
Do you wish to create a custom hardware profile? [no] Starting emulator.
45
sh -c \/usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -accel off &
46
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
47
emulator: WARNING: x86 emulation may not work without hardware acceleration!
48
E0806 18:07:32.811675634    2888 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1596737252.811660834","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
49
emulator: Cold boot: requested by the user
50
Your emulator is out of date, please update by launching Android Studio:
51
 - Start Android Studio
52
 - Select menu "Tools > Android > SDK Manager"
53
 - Click "SDK Tools" tab
54
 - Check "Android Emulator" checkbox
55
 - Click "OK"
56

57
adb shell getprop sys.boot_completed
58
* daemon not running; starting now at tcp:5037
59
* daemon started successfully
60
adb: device offline
61
The process 'adb' failed with exit code 1
62
adb shell getprop sys.boot_completed
63
adb: device offline
64
The process 'adb' failed with exit code 1
65
adb shell getprop sys.boot_completed

**Comment by ychescale9** [comment]
Can you share you workflow please?

**Comment by nzackoya** [comment]
I used the one from the readme 
```
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
```
