### ISSUE TITLE
GitHub Action environment variables don't seem to propagate to the script correctly

### ISSUE THREAD

**Issue by BenHenning** [ReactiveCircus/android-emulator-runner#90]
Hi. I'm running into issues when trying to utilize GitHub Actions environmental variables with android-emulator-runner.

See my GitHub action script with some debugging pieces:

```yaml
name: CI Lint and Tests

# Controls when the action will run. Triggers the workflow on pull request
# events or push events in the develop branch.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      # Push events on develop branch
      - develop

jobs:
  app_emulator_tests:
    name: Espresso Emulator Tests - App Module (Non-Flaky)
    runs-on: macos-10.15
    env:
      TEST_WHITELIST: org.oppia.app.splash.SplashActivityTest
    strategy:
      matrix:
        api-level: [29]
        target: [default]
        profile: [Nexus 6]
        #profile: [Pixel XL]
    steps:
      - name: Test env variable
        run: echo ${TEST_WHITELIST}

      - name: Test env variable 2
        run: echo "Test whitelist ${TEST_WHITELIST}"

      - name: Test env variable 3
        run: echo $TEST_WHITELIST

      - uses: actions/checkout@v2

      - name: Test env variable 4
        run: echo $TEST_WHITELIST

      - uses: actions/cache@v2
        with:
         path: ~/.gradle/caches
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-jars-{{ checksum "build.gradle" }}

      - name: Test env variable 5
        run: echo $TEST_WHITELIST

      # Set up Java 8 since it's required for building binaries dependent on the Android SDK.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test env variable 6
        run: echo $TEST_WHITELIST

      - name: Set up Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7

      - name: Test env variable 7
        run: echo $TEST_WHITELIST

      - name: Set up platform tools
        run: sdkmanager platform-tools

      - name: Test env variable 8
        run: echo $TEST_WHITELIST

      - name: Export environment variable
        run: export TEST_WHITELIST_CONFIG=${TEST_WHITELIST} && echo "Test config here $TEST_WHITELIST_CONFIG"

      - name: Test env variable
        run: echo "Test exported variable $TEST_WHITELIST_CONFIG"

      - name: Run emulator tests
        uses: ReactiveCircus/android-emulator-runner@v2.11.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          profile: ${{ matrix.profile }}
          arch: x86_64
          # Note that 'sudo' is not run here since it will drop necessary
          # environmental variables that were overwritten above to ensure
          # correct access to the Android SDK & home directories.
          # TODO: figure out how to make GitHub env variables work with android-emulator-runner
          script: echo $TEST_WHITELIST_CONFIG; ./scripts/run_emulator_tests.sh $TEST_WHITELIST_CONFIG

      # Upload all test results to GitHub (including detailed reports and videos, if any).
      - uses: actions/upload-artifact@v2
        with:
          name: emulator-test-output
          path: emulator_test_output/

```

I've tried a few different variations of this (e.g. using TEST_WHITELIST instead of TEST_WHITELIST_CONFIG). The echos all print the correct values until the ``script`` line--the environment variables are always empty there. Unusually, other environment variables (like ANDROID_SDK and ANDROID_HOME) _are_ correctly defined and used within the run_emulator_tests.sh script.

Defining the variable right before running the script works, e.g.:
``script: export TEST_WHITELIST_CONFIG="org.oppia.app.splash.SplashActivityTest"; ./scripts/run_emulator_tests.sh $TEST_WHITELIST_CONFIG``

But, this isn't great in terms of flexibility.

Is this an issue with GitHub actions, this action, my configuration, or a combination?

For context, this is my WIP PR: https://github.com/oppia/oppia-android/pull/1844.

**Comment by BenHenning** [comment]
Note that this might actually be an issue with my script. Will follow up with more details after I have a chance to test.

**Comment by BenHenning** [comment]
This does seem like an issue: I ended up needing to go with a custom solution since GitHub environment variables don't seem visible to the 'script' part of the action.

**Comment by ychescale9** [comment]
I have `echo $GITHUB_REPOSITORY` in the test workflow for this action and it [seems to work](https://github.com/ReactiveCircus/android-emulator-runner/runs/1139878230?check_suite_focus=true).

I just tested referencing the environment variable from a separate script file and it [also seems to work](https://github.com/ReactiveCircus/android-emulator-runner/runs/1153548331?check_suite_focus=true).

I'll have a look at your PR and see if I can find the issue.

**Comment by Kiruel** [comment]
I got the same problem here, trying to pass variable into the job, but the script do not have the variable in the env:

```yaml
      - name: Run Flutter Driver tests
        env:
          TEST_ENV: "toto"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          arch: x86_64
          working-directory: ${{ matrix.path }}
          api-level: ${{ matrix.api-level }}
          script: sudo flutter drive --driver=test_driver/integration_test.dart --target=integration_test/login_success_test.dart
```

And in my gradle:

```gradle
    println String.valueOf(System.getenv('TEST_ENV'))
```
Result:
```bash
null
```

And if I do the:
```yaml
    script: export TEST_ENV="toto"; sudo flutter drive --driver=test_driver/integration_test.dart --target=integration_test/login_success_test.dart
```
My result is still:
```bash
null
```
